# Generated by Django 5.1.6 on 2025-03-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfterQuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Этот текст будет показан пользователю после ввода вопроса и ФИО. Здесь можно попросить указать контактную информацию.', verbose_name='Текст после вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Текст после вопроса',
                'verbose_name_plural': 'Текст после вопроса',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('media', models.FileField(blank=True, null=True, upload_to='company/', verbose_name='Медиа')),
                ('media_type', models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео')], max_length=10, null=True, verbose_name='Тип медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('media', models.FileField(blank=True, null=True, upload_to='event/', verbose_name='Медиа')),
                ('media_type', models.CharField(blank=True, choices=[('photo', 'Фото'), ('video', 'Видео')], max_length=10, null=True, verbose_name='Тип медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Информация о мероприятии',
                'verbose_name_plural': 'Информация о мероприятии',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='experts/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('scheduled_time', models.DateTimeField(verbose_name='Время отправки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID Telegram')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('real_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('contacts', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактная информация')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='Авторизован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Приветственное сообщение',
                'verbose_name_plural': 'Приветственное сообщение',
            },
        ),
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Ссылка компании',
                'verbose_name_plural': 'Ссылки компании',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос опроса',
                'verbose_name_plural': 'Вопросы опроса',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='events.surveyquestion')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.survey', verbose_name='Опрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='events.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на опрос',
                'verbose_name_plural': 'Ответы на опросы',
                'ordering': ['-created_at'],
                'unique_together': {('survey', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Отвечен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.expert', verbose_name='Эксперт')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.speaker', verbose_name='Спикер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyOptionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.surveyquestion', verbose_name='Вопрос')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.surveyquestionoption', verbose_name='Выбранный вариант')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_responses', to='events.surveyresponse', verbose_name='Ответ на опрос')),
            ],
            options={
                'verbose_name': 'Выбранный вариант',
                'verbose_name_plural': 'Выбранные варианты',
                'ordering': ['question__order'],
                'unique_together': {('response', 'question')},
            },
        ),
    ]
