# Generated by Django 5.1.6 on 2025-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_session_alter_speaker_options_speaker_is_moderator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Эксперт', 'verbose_name_plural': 'Эксперты'},
        ),
        migrations.AddField(
            model_name='expert',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
