# Generated by Django 5.1.6 on 2025-03-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_speaker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='contacts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактная информация'),
        ),
    ]
