# Generated by Django 5.1.6 on 2025-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='experts/', verbose_name='Фото'),
        ),
    ]
