# Generated by Django 5.1.6 on 2025-03-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_telegramuser_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterQuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Этот текст будет показан пользователю после ввода вопроса и ФИО. Здесь можно попросить указать контактную информацию.', verbose_name='Текст после вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Текст после вопроса',
                'verbose_name_plural': 'Текст после вопроса',
            },
        ),
    ]
