# Generated by Django 5.1.6 on 2025-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_expert_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='Авторизован'),
        ),
    ]
