# Generated by Django 5.1.6 on 2025-03-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_expert_options_expert_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Спикер', 'verbose_name_plural': 'Спикеры'},
        ),
        migrations.AddField(
            model_name='speaker',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
